name: Build

on:
  push:
    branches:
      - master

env:
  ONNXRUNTIME_ROOT: onnxruntime-osx-x86_64-1.12.1

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install cmake ninja opencv onnxruntime

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=$(brew --prefix)/bin/ninja -G Ninja -S . -B build

      - name: Link
        run: ninja
        working-directory: build
